export { default as Header } from "./Header/Header.component";
export { default as About } from "./About/About.component";
export { default as Skills } from "./Skills/Skills.component";
export { default as Projects } from "./Projects/Projects.component";
export { default as Contact } from "./Contact/Contact.component";
export { default as RevealText } from "./RevealText/RevealText.component";
export { default as AnimatedButton } from "./AnimatedButton/AnimatedButton.component";
export { default as FeaturedProjectBento } from "./FeaturedProjectBento/FeaturedProjectBento.component";
export { default as FeaturedProjectHorizontal } from "./FeaturedProjectHorizontal/FeaturedProjectHorizontal.component";
